# Read about how to use this configuration file
# https://developers.cloudflare.com/workers/cli-wrangler/configuration

name = "worker-typescript-template"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2022-04-08"

[vars]
EXAMPLE_ENVIRONMENT_VARIABLE = "Hello, World!"

[[kv_namespaces]]
binding = ""
preview_id = ""
id = ""

[build]
command = "npm run webpack"
[build.upload]
format = "service-worker"
