# Read about how to use this configuration file
# https://developers.cloudflare.com/workers/wrangler/configuration

name = "worker-typescript-template"
main = "dist/index.mjs"
account_id = ""
compatibility_date = "2022-09-10"
compatibility_flags = []

[triggers]
  crons = ["0 * * * *"]

[vars]
  EXAMPLE_ENVIRONMENT_VARIABLE = "Hello, World!"

[[kv_namespaces]]
  binding = "<NAMESPACE_NAME>"
  id = "<NAMESPACE_ID>"
  preview_id = "<NAMESPACE_PREVIEW_ID>"

[build]
  command = "pnpm run build"

[miniflare]
  kv_persist = true
  cache_persist = true
